### ISSUE TITLE
getCommitHash is an unreliable proof that _prevPollID exists

### ISSUE THREAD

**Issue by niran** [ConsenSys/PLCRVoting#22]
In `commitVote`, we check to ensure that the insert position (`_prevPollID`) actually exists by checking `getCommitHash(msg.sender, _prevPollID) != 0`. If a user sets their commit hash for that poll to zero, that check will fail even though it is a valid insertion position.

**Recommendation**

Use `DLL.contains` to verify that `_prevPollID` is a valid insertion position.

**Comment by kangarang** [comment]
i love you

**Comment by yorhodes** [comment]
The same check is performed in hasBeenRevealed, as per: https://github.com/ConsenSys/PLCRVoting/commit/b2ae12779ba5344b723f42d821e6b9cede3ee088

**Comment by niran** [comment]
Yikes, good catch. That commit locks your tokens if you set your commit hash to zero.

**Comment by niran** [comment]
It seems like the cause of this class of issues is that there's a desire to distinguish polls that were never voted on from polls that were voted on and revealed. I think a better way to do this is to maintain attributes that aren't controlled by user input. For instance, you could have `committed` and `revealed` attributes that are set to true when those events happen. Rather than use an attribute for `unlocked`, using `DLL.contains(pollID)` as the locked state ensures that tokens can always be rescued if they're in the list. This gives a few possible states:

**all false**: never voted
**committed, but not revealed or unlocked**: waiting for a reveal or a rescue
**committed, revealed and unlocked**: user revealed on time
**committed, not revealed, but unlocked**: user rescued tokens

 Here's what would happen to each `hasBeenRevealed` call:

`rescueTokens`: if `DLL.contains(_pollID)` and `isExpired(pollMap[_pollID].revealEndDate)`, remove the poll ID from the list
`revealVote`: if `committed` is true and `revealed` is false, reveal the vote and set `revealed` to true
`getNumPassingTokens`: if `revealed` is true, get the number of tokens they used to vote

Attempting to generalize `hasBeenRevealed` risks locking up tokens. Replacing it with explicit conditions for each case is safer.

**Comment by kangarang** [comment]
https://github.com/ConsenSys/PLCRVoting/commit/1fec53b876156d8f219d09c5bc871e83c14b4fee
