### ISSUE TITLE
Use "tokens/eip20/EIP20Interface.sol" instead of "tokens/eip20/EIP20.sol"

### ISSUE THREAD

**Issue by suhabe** [ConsenSys/PLCRVoting#24]
If PLCRVoting works with any EIP20 token, use the EIP20Interface type rather than ConsenSys's specific implementation of it.

**Comment by kangarang** [comment]
https://github.com/ConsenSys/PLCRVoting/commit/079c75d08940dfb453cf5f46c7f57477a2487571
