### ISSUE TITLE
Integer overflow in startPoll

### ISSUE THREAD

**Issue by niran** [ConsenSys/PLCRVoting#25]
`commitEndDate: block.timestamp + _commitDuration` and `revealEndDate: block.timestamp + _commitDuration + _revealDuration` can overflow. This can result in polls that will accept votes, but never unlock tokens in the current code.

**Recommendation**

Use SafeMath for arithmetic.

**Comment by kangarang** [comment]
https://github.com/ConsenSys/PLCRVoting/commit/26579ec7f645f868cdb4c7de4c764808882a5d3a
