### ISSUE TITLE
pollExists is misleading and incomplete

### ISSUE THREAD

**Issue by niran** [ConsenSys/PLCRVoting#26]
`pollExists` doesn't check if a poll exists. It attempts to check if a poll's stage times are reasonable, but misses polls that allow users to commit to a vote later than they can reveal their vote, which would lock their tokens permanently.

**Recommendation**

In `startPoll`, require reasonable stage times. Both must be greater than `block.timestamp`, and `commitEndDate` must be less than `revealEndDate`. Remove sanity checks from `pollExists` and just require that `_pollID <= pollNonce` so users can't vote on polls that haven't been started yet.

**Comment by kangarang** [comment]
https://github.com/ConsenSys/PLCRVoting/commit/a069730fcd818c249574a38f922e871c8011fc4f
