### ISSUE TITLE
Documentation of startPoll does not match implementation

### ISSUE THREAD

**Issue by nickreynolds** [ConsenSys/PLCRVoting#43]
The documentation (README) for "Start Poll" states "The process begins with a poll, which only the contract owner can create, centered upon some proposal."  Later in the README, we also see "requires that the msg.sender is the deployer (owner) of the plcr instance".

However, the implementation of `startPoll` (`function startPoll(uint _voteQuorum, uint _commitDuration, uint _revealDuration) public returns (uint pollID) {`) does not seem to require that the msg.sender is the owner of the plcr instance. In fact, the plcr instance does not seem to maintain a reference to its deployer/owner at all.

Am I missing something? Was this restriction removed?

**Comment by skmgoldin** [comment]
The documentation on this repo is stale. There's some more up-to-date documentation on PLCR here: https://github.com/skmgoldin/tcr/blob/master/owners_manual.md

Hopefully we'll update this documentation in the upcoming 2.0 release.
