### ISSUE TITLE
README.md - fix typo in Poll Ended description 

### ISSUE THREAD

**Issue by strictlymomo** [ConsenSys/PLCRVoting#47]
The description appears to have been cut off.

<img width="818" alt="screen shot 2018-05-18 at 1 46 54 pm" src="https://user-images.githubusercontent.com/8671427/40250133-53fcdcae-5aa3-11e8-9d16-d96e9665bba9.png">

Please also expand description to explain how tokens are forfeited or divvied among voters (if relevant to this scope).

**Comment by kangarang** [comment]
hi @strictlymomo , thank you for addressing this. we are updating the docs on [this branch](https://github.com/ConsenSys/PLCRVoting/tree/update-docs) and should have it pushed to master in a few days. please don't hesitate to ask if you have any further questions.

another resource: https://medium.com/metax-publication/a-walkthrough-of-the-adchain-registry-tcr-in-solidity-72addcde17fb

**Comment by kangarang** [comment]
moved to [develop branch](https://github.com/ConsenSys/PLCRVoting/tree/develop)
