### ISSUE TITLE
pollEnded returns true when invoked with pollIDs of non-existant polls

### ISSUE THREAD

**Issue by kangarang** [ConsenSys/PLCRVoting#7]
```
    it('should throw an error if the poll does not exist', async () => {
      const plcr = await utils.getPLCRInstance();

      const options = defaultOptions();
      options.actor = bob;

      try {
        const ended = await plcr.pollEnded.call('9001'); // this returns true
        assert(false, 'should have thrown error for non-existant poll #9001');
      } catch (err) {
        assert(utils.isEVMException(err), err.toString());
      }
    });

```

**Comment by kangarang** [comment]
This is causing the bug experienced in #5

**Comment by skmgoldin** [comment]
https://github.com/ConsenSys/PLCRVoting/commit/950424fbaf1940311049c3cba52ecaeb8129108c

Lets review this before merging to master, I'm not sure I've convinced myself this is the best solution. It works, but lets at least think about what might be better and make a note of it to implement later.

**Comment by yorhodes** [comment]
Not sure if this is "better," but you could lower the responsibility of checking uninitialized values to a requirement in isExpired to keep the code DRY-er.

**Comment by kangarang** [comment]
Indeed, implementing the check in `isExpired` is cleaner, and all tests pass.

```
function isExpired(uint _terminationDate) constant public returns (bool expired) {
    require(_terminationDate > 0);
    return (block.timestamp > _terminationDate);
}
```

I like this solution! @skmgoldin, how should we proceed?

**Comment by skmgoldin** [comment]
Good advice @yorhodes. We decided to add an explicit function for it. Doing it in `isExpired` seemed slightly non-idiomatic to that function's purpose.

https://github.com/ConsenSys/PLCRVoting/commit/b1a05e8ace28a5a6b991ba0435389a4dd73568b8
